accountregistrations/api/urls.py
from django.conf.urls import url
from .views import LoginView, UserProfile, SignUpView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^detail/$', UserProfile.as_view(), name="user-details"),
    url(r'^signup/$', SignUpView.as_view(), name="signup"),
    ]

accountregistrations/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from accountregistrations import views
from django.conf import settings


urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^signupManager/$', views.signup1, name='signup1'),
    
    url(r'^login/$', views.Login, name='Login'),

    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),

    # -----------For gmail login-------------
    url(r'^auth/complete/google-oauth2/Usertype/$', views.Usertype, name='Usertype'),

    # -----------For Facebook login-----------
    url(r'^auth/complete/facebook/Usertype/$', views.Usertype, name='Usertype'),

    # -------------For Password Reset----------------------

    url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'registrations/password_reset_form.html'},
        name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done,
        {'template_name': 'registrations/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name': 'registrations/password_reset_confirm.html'},
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,
        {'template_name': 'registrations/password_reset_complete.html'}, name='password_reset_complete'),

    # ------------ For knowing the type of users-------------
    url(r'^login/Usertype/$', views.Usertype, name='Usertype'),
    url(r'^api/user/', include('accountregistrations.api.urls', namespace = 'api-user-login'))

]

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #for UN-authenticated user
    url(r'^cart_detail/$', views.cart_detail, name='cart_detail'),
    url(r'^cart_add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^cart_remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),

    #for authenticated user
    url(r'^$', views.view_cart, name='view_cart'),
    url(r'^add/(?P<product_id>\d+)/$', views.add_to_cart, name='add_to_cart'),
    url(r'^update_quantity/(?P<product_id>\d+)/$', views.update_quantity, name='update_quantity'),
    url(r'^remove/(?P<product_id>\d+)/$', views.remove_from_cart, name='remove_from_cart'),
]

darshan/urls.py
from django.conf.urls import url, include
from darshan import views


urlpatterns = [

    url(r'^$', views.home, name='home'),
    url(r'^user_profile/$', views.user_profile, name='user_profile'),
    url(r'^manager_profile/$', views.manager_profile, name='manager_profile'),
    url(r'^selectedDarshan/$', views.selectedDharshan, name='accounts'),
    url(r'^details/(?P<temp>.+)$', views.details, name='details'),
    url(r'^detail/(?P<temp1>.+)$', views.detail, name='detail'),
    url(r'^selectedTemple/(?P<pk>\d+)$', views.selectedTemple, name='selectedTemple'),
    url(r'^allPrasad/(?P<pk>\d+)$', views.all_Prasad, name='all_Prasad'),
    url(r'^delete/(?P<value>.+)/$', views.delete, name='delete'),
    url(r'^temple_gallery/2col$', views.temple_gallery_2col, name='temple_gallery_2col'),
    url(r'^temple_gallery/default$', views.temple_gallery_default, name='temple_gallery_default'),
    # ------------ For Temples--------
    url(r'^temple_add/$', views.temple_add, name='temple_add'),
    url(r'^temple_update/(?P<s>.+)/$', views.temple_update, name='temple_update'),
    url(r'^temple_remove/(?P<s>.+)/$', views.temple_remove, name='temple_remove'),

    # ------------- For Pictures----------
    url(r'^picture_add/$', views.picture_add, name='picture_add'),
    url(r'^picture_update/(?P<s1>.+)/$', views.picture_update, name='picture_update'),
    url(r'^picture_remove/(?P<s1>.+)/$', views.picture_remove, name='picture_remove'),

    # -----------For Darshans------------
    url(r'^darshan_add/$', views.darshan_add, name='darshan_add'),
    url(r'^darshan_update/(?P<s2>.+)/$', views.darshan_update, name='darshan_update'),
    url(r'^darshan_remove/(?P<s2>.+)/$', views.darshan_remove, name='darshan_remove'),
    url(r'^alldarshan/$', views.allDarshan, name='alldarshan'),

    # ----------------For Prasad-----------------

    url(r'^prasad_add/$', views.prasad_add, name='prasad_add'),
    url(r'^prasad_update/(?P<p>.+)/$', views.prasad_update, name='prasad_update'),
    url(r'^prasad_remove/(?P<p>.+)/$', views.prasad_remove, name='prasad_remove'),

    url(r'^tmp/', include('darshan.api.urls', namespace='temple'))

]

notify/urls.py
try:
    from django.conf.urls import url
except ImportError:
    from django.urls import url

from notify import views as nf

app_name = 'notifications'


urlpatterns = [
    url(r'^all/$', nf.notifications, name="all"),
    url(r'^api/update/$', nf.notification_update, name="update"),
    url(r'^mark/(?P<pk>\d+)/$', nf.mark, name='mark'),
    url(r'^mark-all/$', nf.mark_all, name='mark_all'),
    url(r'^delete/(?P<pk>\d+)/$', nf.delete, name='delete'),
    url(r'^rdr/(?P<notification_id>[\d]+)/$', nf.read_and_redirect,
        name='read_and_redirect'),
]

shop/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth import views as auth_views
from darshan import views
from shop import views as core_views
from django.conf import settings

urlpatterns = [
    url(r'^allproducts/$', core_views.allproducts, name='allproducts'),
    url(r'^productdetails/(?P<pk>\d+)$', core_views.details1, name='details1'),

    # ----------For Shopkeeper-------------
    url(r'^seller_profile/$', core_views.seller_profile, name='seller_profile'),

    # ------------ For Shopkeeper--------
    url(r'^product_add/$', core_views.product_add, name='product_add'),
    url(r'^product_update/(?P<p>.+)/$', core_views.product_update, name='product_update'),
    url(r'^product_remove/(?P<p>.+)/$', core_views.product_remove, name='product_remove'),
    url(r'^product_api/', include('shop.api.urls'), name='product_api'),

]

temple/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from shop import views as core_views
#from django.views.i18n import javascript_catalog


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('accountregistrations.urls', namespace='accountregistrations')),
    url(r'', include('darshan.urls', namespace='darshan')),
    url(r'', include('shop.urls', namespace='shop')),
    url(r'cart/', include('cart.urls', namespace='cart')),
    url(r'orders/', include('orders.urls', namespace='orders')),
    url(r'^notifications/', include('notify.urls', namespace='notifications')),
    #url(r'^pay/', include('payu_biz.urls', namespace='pay')),
    #url(r'^search/', include('haystack.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url('^', include('django.contrib.auth.urls')),
    #url(r'^admin/jsi18n', javascript_catalog),
    url(r'^api/temple/', include('darshan.api.urls', namespace='api-temple')),

]

urlpatterns += [
       url(r'^api-auth/', include('rest_framework.urls'))
]
handler400 = core_views.error400  # noqa
handler403 = core_views.error403  # noqa
handler404 = core_views.error404  # noqa
handler500 = core_views.error500  # noqa
handler200 = core_views.error200  # noqa


# when debug is True

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG is False:
#     urlpatterns += [url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
#                     url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}), ]

accountregistrations/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.postgres.fields import ArrayField
from dirtyfields import DirtyFieldsMixin


# Create your models here.


class Mobile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Mobile_Number = models.CharField(max_length=15,default=0)
    email_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    @receiver(post_save, sender=User)
    def create_user_mobile(sender, instance, created, **kwargs):
        if created:
            Mobile.objects.create(user=instance)


class ContactInspire(models.Model):
    Name = models.CharField(max_length=100, default=None)
    Email = models.CharField(max_length=400, default=None)
    Comment = models.TextField()

    def __str__(self):
        return self.Name

accountregistrations/forms.py
from django import forms
from .models import ContactInspire, Mobile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password1', 'password2', 'email',)

    def __init__(self, *args, **kwargs):

        super(SignUpForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            username ="username"
            help_text = self.fields[field].help_text
            self.fields[field].help_text = None
            if help_text != '':
                self.fields[field].widget.attrs.update(
                    {'class': 'has-popover', 'data-content' :help_text, 'data-placement': 'right',
                     'data-container': 'body'})
                self.fields[username].widget.attrs.update(
                    {'id': username})

                # to ensure that the user email is unique
    # def clean_email(self):
    #     if User.objects.filter(email=self.cleaned_data.get('email', None)).count() > 0:
    #         raise forms.ValidationError("User with this email already exists")

    #     return self.cleaned_data.get('email')

class MobileForm(forms.ModelForm):
    Mobile_Number = forms.CharField(max_length=15,required=True)
    class Meta:
        model = Mobile
        fields = ('Mobile_Number',)

class contactInspireForm(forms.ModelForm):
    class Meta:
        model= ContactInspire
        fields = ('Name','Email','Comment')

accountregistrations/api/views.py
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.generics import ListAPIView, ListCreateAPIView
from rest_framework.response import Response

from accountregistrations.api.serializers import UserSerializer,MobileSerializer, UserDetailsSerilaizer, SignUpSerializer
from accountregistrations.models import Mobile


class LoginView(ObtainAuthToken):
    # queryset = User.objects.all()
    # serializer_class = UserSerializer
    def auth_login(self, request, *args, **kwargs):
        serializer = self.serializer_class(data = request.data, context ={
            'request': request
        })
        serializer.is_valid(raise_exception = True)
        user = serializer.validated_data['user']
        token = Token.objects.get_or_create(user = user)
        return Response({
            'token': token
        })

class UserProfile(ListAPIView):
    queryset = User.objects.all()
    # queryset = Mobile.objects.all()

    serializer_class = UserDetailsSerilaizer
    # serializer_class = MobileSerializer

class SignUpView(ListCreateAPIView):
    queryset = User.objects.all()
    serializer_class = SignUpSerializer

accountregistrations/templates/accountregistrations/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:
If the link does not appear clickable then copy the link and open it on new tab.

http://{{ domain }}{% url 'accountregistrations:activate' uidb64=uid token=token %}
{% endautoescape %}

accountregistrations/templates/accountregistrations/account_activation_invalid.html
{% extends 'accountregistrations/newbase.html' %}
{% load staticfiles %}
{% block content2 %}
<div id="peace-layout">
    {% include 'accountregistrations/header.html' %}
    <h2 align="center">The confirmation link was invalid, possibly because it has already been used.</h2>
</div>
{% endblock %}

accountregistrations/templates/accountregistrations/account_activation_sent.html
{% extends 'accountregistrations/newbase.html' %}
{% load staticfiles %}
{% block content2 %}
<div id="peace-layout">
    {% include 'accountregistrations/header.html' %}
    <div class="container" style="margin-top: 15px;">
        <div class="row" style="text-align: center">
            <div class="col-md-12" align="center">
                <br>
                <h1 style="color: green">Please confirm your email address to complete the registration.</h1>
                <br>
                <h2 style="color: red;text-align: center;padding-bottom: 40px;">
                    If you don't receive confirmation mail within 1 day, 
                    please mail us your username and email with which you have made your account. 
                    We'll check and revert.
                </h2>
            </div>
        </div>
    </div>

</div>
{% endblock %}

accountregistrations/templates/accountregistrations/header.html
{% load staticfiles %}
{% load notification_tags %}
<header id="top-section">
    <div class="container">
        <div class="col-sm-4 hidden-xs address">
            <div class="pull-left">
                <ul>
                    <li><i class="fa fa-phone"></i> +91 7990712559</li>
                    <li><i class="fa fa-envelope-o"></i> inspire@startinspire.com</li>
                </ul>
            </div>
            <!-- pull left  -->
        </div>
        <!-- /.address -->

        <div class="col-sm-4 col-xs-12">
            <div class="logo text-center">
                <a href="{% url 'darshan:home' %}"> <img src="{% static 'images/logo-08.png' %}" alt="Peace"/> </a>
            </div>
            <!-- /.logo -->
        </div>
        <!-- col sm 4 -->

        <div class="social-search pull-right hidden-xs">
            <ul>
                <li><a href="#"><i class="fa fa-facebook"></i><span></span></a>
                </li>
                <li><a href="#"><i class="fa fa-twitter"></i><span></span></a>
                </li>
                <li><a href="#"><i class="fa fa-google-plus"></i><span></span></a>
                </li>
                <li><a href="#"><i class="fa fa-pinterest"></i><span></span></a>
                </li>
            </ul>

            <div id="site-search">
                <a href="#"><i class="fa fa-search"></i></a>
                <form class="search-form" action="#" method="get">
                    <input type="text" name="s" id="topSearchField" class="form-control" value=""
                           placeholder="Type &amp; Hit Enter...">
                    <i class="fa fa-close"></i>
                </form>
            </div>
            <!--   site search  -->
            <div id="notifications" style="float: right;padding-right: 60px;color:lightgrey;">
                <a href="{% url 'notifications:all' %}">
                    <i class="fa fa-bell" aria-hidden="true" style="color: #949391"></i><span>{% if user|notifications_unread > 0 %}
                    {{ user|notifications_unread }}
                {% else %}0{% endif %}</span>
                </a>
            </div>


            <div id="top-cart">

                {% if user.is_authenticated  and not user.is_superuser and not user.templemanager.is_manager and not user.shopkeeper.is_shopkeeper %}

                    <a href="{% url 'cart:view_cart' %}" id="top-cart-trigger" class="hd-icons">
                        <i class="fa fa-shopping-cart"></i><span>{% if total_items > 0 %}{{ total_items }}{% else %}
                        0{% endif %}</span>
                    </a>

                    {#                <div class="top-cart-content">#}
                    {#                    <div class="top-cart-title">#}
                    {#                        <h4>Shopping Cart</h4>#}
                    {#                    </div>#}
                    {#                    <!-- top cart  -->#}
                    {##}
                    {#                    <div class="top-cart-items">#}
                    {#                       {% if total_items > 0 %}#}
                    {#                        <div >You have {{ total_items }} items in the cart.</div>#}
                    {#                       {% else %}#}
                    {#                        <div class="empty">No products in the cart.</div>#}
                    {#                        {% endif %}#}
                    {#                    </div>#}
                    {#                    <!-- top cart item -->#}
                    {#                </div>#}
                    <!-- top cart content -->
                {% elif not user.is_authenticated and not user.is_superuser %}
                    <a href="{% url 'cart:cart_detail' %}" id="top-cart-trigger" class="hd-icons">
                        <i class="fa fa-shopping-cart"></i>
                        <span>{% with total_items=cart|length %}{% if cart|length > 0 %}{{ total_items }}{% else %}0
                        {% endif %}{% endwith %}</span>
                    </a>

                    {#                <div class="top-cart-content">#}
                    {#                    <div class="top-cart-title">#}
                    {#                        <h4>Shopping Cart</h4>#}
                    {#                    </div>#}
                    {#                    <!-- top cart  -->#}
                    {##}
                    {#                    <div class="top-cart-items">#}
                    {#                       {% if total_items > 0 %}#}
                    {#                        <div>You have {{ total_items }} items in the cart.</div>#}
                    {#                       {% else %}#}
                    {#                        <div class="empty">No products in the cart.</div>#}
                    {#                        {% endif %}#}
                    {#                    </div>#}
                    {#                    <!-- top cart item -->#}
                    {#                </div>#}
                {% endif %}
            </div>
            <!--  top cart  -->
        </div>
        <!-- social search  -->
    </div>
    <!-- menu slider start -->
    <div class="menu-slider">
        <nav id="peace-menu">
            <div class="container">

                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#responsive-icon" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <!-- end navbar head -->

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="responsive-icon">
                    <div class="menu-menu-1-container">
                        <ul class="nav navbar-nav text-center nav navbar-nav text-center">
                            <li class="active">
                                <a title="Home" href="{% url 'darshan:home' %}">
                                    Home
                                </a>
                            </li>
                            <li>
                                <a title="Sermons" href="{% url 'darshan:alldarshan' %}">
                                    Darshan
                                </a>
                            </li>
                            {% if user.is_authenticated  and not user.is_superuser and not user.templemanager.is_manager and not user.shopkeeper.is_shopkeeper or not user.is_authenticated %}
                                <li>
                                    <a title="Shop" href="{% url 'shop:allproducts' %}">
                                        Shop
                                    </a>
                                </li>
                            {% endif %}
                            <li class="dropdown">
                                <a title="Gallery" href="#" data-toggle="dropdown"
                                   class="dropdown-toggle" aria-haspopup="true">Gallery
                                    <i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class=" dropdown-menu">
                                    <li><a title="Gallery 2 Columns" href="{% url 'darshan:temple_gallery_2col' %}">Gallery 2
                                        Columns</a>
                                    </li>
                                    <li><a title="Gallery Default" href="{% url 'darshan:temple_gallery_default' %}">Gallery Default</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a title="Events" href="#" data-toggle="dropdown"
                                   class="dropdown-toggle" aria-haspopup="true">Events <i
                                        class="fa fa-angle-down"></i></a>
                                <ul role="menu" class=" dropdown-menu">
                                    <li><a title="Event Defaults" href="#">Event Single</a>
                                    </li>
                                    <li><a title="Event Defaults" href="#">Event Two Column</a>
                                    </li>
                                    <li><a title="Event Defaults" href="#">Event Three
                                        Column</a>
                                    </li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a title="Causes" href="#" data-toggle="dropdown"
                                   class="dropdown-toggle" aria-haspopup="true">Causes <i
                                        class="fa fa-angle-down"></i></a>
                                <ul role="menu" class=" dropdown-menu">
                                    <li><a title="Causes 2 Col" href="#">Causes single</a>
                                    </li>
                                    <li><a title="Causes 3 Col" href="#">Causes 2 Col</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a title="News/Blog" href="#" data-toggle="dropdown"
                                   class="dropdown-toggle" aria-haspopup="true">News/Blog <i
                                        class="fa fa-angle-down"></i></a>
                                <ul role="menu" class=" dropdown-menu">
                                    <li><a title="Blog Default" href="#">Blog Default</a>
                                    </li>
                                    <li><a title="Blog 2 Columns" href="#">Blog 2 Columns</a>
                                    </li>
                                </ul>
                            </li>
                            {% if user.is_authenticated %}
                                {% if user.shopkeeper.is_shopkeeper %}
                                    <li class="dropdown">
                                        <a title="profile" href="{% url 'shop:seller_profile' %}">Profile</a>
                                    </li>
                                {% endif %}
                                {% if user.templemanager.is_manager %}
                                    <li>
                                        <a href="{% url 'darshan:manager_profile' %}">
                                            Profile</a>
                                    </li>
                                {% endif %}
                                {% if not user.is_superuser and not user.templemanager.is_manager and not user.shopkeeper.is_shopkeeper %}
                                    <li class="dropdown">
                                        <a href="{% url 'darshan:user_profile' %}">
                                            Profile
                                        </a>
                                    </li>
                                {% endif %}
                                <li class="dropdown"><a title="logout" href="{% url 'accountregistrations:logout' %}">logout</a>
                                </li>
                            {% else %}
                                <li>
                                    <a title="Register" href="{% url 'accountregistrations:Login' %}">
                                        Register
                                    </a>
                                </li>
                            {% endif %}
                            <li class="button-skew"><a class="donate-button" href="#"><span> Donate Now <i
                                    class="fa fa-heart"></i></span></a>
                            </li>
                        </ul>
                    </div>
                    <!-- end menu-1-container -->
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- end container -->
        </nav>
        <!-- /#peace-menu -->
    </div>
    <!-- /.menu-slider -->
</header>