accountregistrations/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from accountregistrations import views
from django.conf import settings


urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^signupManager/$', views.signup1, name='signup1'),
    
    url(r'^login/$', views.Login, name='Login'),

    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),

    # -----------For gmail login-------------
    url(r'^auth/complete/google-oauth2/Usertype/$', views.Usertype, name='Usertype'),

    # -----------For Facebook login-----------
    url(r'^auth/complete/facebook/Usertype/$', views.Usertype, name='Usertype'),

    # -------------For Password Reset----------------------

    url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'registrations/password_reset_form.html'},
        name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done,
        {'template_name': 'registrations/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name': 'registrations/password_reset_confirm.html'},
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,
        {'template_name': 'registrations/password_reset_complete.html'}, name='password_reset_complete'),

    # ------------ For knowing the type of users-------------
    url(r'^login/Usertype/$', views.Usertype, name='Usertype'),
    url(r'^api/user/', include('accountregistrations.api.urls', namespace = 'api-user-login'))

]

cart/api/urls.py
from django.conf.urls import url
from .views import LoginView, UserProfile, SignUpView

urlpatterns = [
    url(r'^detail/$', UserProfile.as_view(), name="cart-details"),
    url(r'^detail/$', UserProfile.as_view(), name="user-details"),
    url(r'^detail/$', UserProfile.as_view(), name="user-details"),

]

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #for UN-authenticated user
    url(r'^cart_detail/$', views.cart_detail, name='cart_detail'),
    url(r'^cart_add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^cart_remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),

    #for authenticated user
    url(r'^$', views.view_cart, name='view_cart'),
    url(r'^add/(?P<product_id>\d+)/$', views.add_to_cart, name='add_to_cart'),
    url(r'^update_quantity/(?P<product_id>\d+)/$', views.update_quantity, name='update_quantity'),
    url(r'^remove/(?P<product_id>\d+)/$', views.remove_from_cart, name='remove_from_cart'),
]

orders/urls.py
from django.conf.urls import url
from . import views
'^'

urlpatterns = [
	url(r'^online_donation/(?P<v>.+)/$',views.Online_Donation, name='Online_Donation'),
    url(r'^order_create/$', views.order_create, name='order_create'),
    url(r'^payment/$',views.payment, name='payment'),

    url(r'^payment/success$', views.payment_success, name="payment_success"),
    url(r'^payment/failure$', views.payment_failure, name="payment_failure"),

    

]

shop/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth import views as auth_views
from darshan import views
from shop import views as core_views
from django.conf import settings

urlpatterns = [
    url(r'^allproducts/$', core_views.allproducts, name='allproducts'),
    url(r'^productdetails/(?P<pk>\d+)$', core_views.details1, name='details1'),

    # ----------For Shopkeeper-------------
    url(r'^seller_profile/$', core_views.seller_profile, name='seller_profile'),

    # ------------ For Shopkeeper--------
    url(r'^product_add/$', core_views.product_add, name='product_add'),
    url(r'^product_update/(?P<p>.+)/$', core_views.product_update, name='product_update'),
    url(r'^product_remove/(?P<p>.+)/$', core_views.product_remove, name='product_remove'),
    url(r'^product_api/', include('shop.api.urls'), name='product_api'),

]

temple/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from shop import views as core_views
#from django.views.i18n import javascript_catalog


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('accountregistrations.urls', namespace='accountregistrations')),
    url(r'', include('darshan.urls', namespace='darshan')),
    url(r'', include('shop.urls', namespace='shop')),
    url(r'cart/', include('cart.urls', namespace='cart')),
    url(r'orders/', include('orders.urls', namespace='orders')),
    url(r'^notifications/', include('notify.urls', namespace='notifications')),
    #url(r'^pay/', include('payu_biz.urls', namespace='pay')),
    #url(r'^search/', include('haystack.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url('^', include('django.contrib.auth.urls')),
    #url(r'^admin/jsi18n', javascript_catalog),
    url(r'^api/temple/', include('darshan.api.urls', namespace='api-temple')),

]

urlpatterns += [
       url(r'^api-auth/', include('rest_framework.urls'))
]
handler400 = core_views.error400  # noqa
handler403 = core_views.error403  # noqa
handler404 = core_views.error404  # noqa
handler500 = core_views.error500  # noqa
handler200 = core_views.error200  # noqa


# when debug is True

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG is False:
#     urlpatterns += [url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
#                     url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}), ]

cart/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField, JSONField
from django.contrib.auth.models import User
import datetime

from django.contrib.auth.models import User
from django.db import models
from shop.models import Product


class Carts(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return 'Cart #' + str(self.id) + ',' +str(self.user.username)


class CartItem(models.Model):
    cart = models.ForeignKey(Carts, null=True, blank=True)
    product = models.ForeignKey(Product)
    quantity = models.IntegerField(default=0)
    active = models.BooleanField(default=True)

    def __str__(self):
        return 'Order #' + str(self.id) + ' of ' + self.product.Product_Name

    

cart/forms.py
from django import forms
from .models import CartItem


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,21)]


class CartAddProductForm(forms.ModelForm):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    class Meta:
        model = CartItem
        fields = ('quantity', )


PRODUCT_QUANTITY_CHOICES1 = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForms(forms.Form):#--------For Anonymous User---------------------------
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES1, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/api/views.py
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.generics import ListAPIView, ListCreateAPIView
from rest_framework.response import Response

from accountregistrations.api.serializers import UserSerializer,MobileSerializer, UserDetailsSerilaizer, SignUpSerializer
from accountregistrations.models import Mobile


class LoginView(ObtainAuthToken):
    # queryset = User.objects.all()
    # serializer_class = UserSerializer
    def auth_login(self, request, *args, **kwargs):
        serializer = self.serializer_class(data = request.data, context ={
            'request': request
        })
        serializer.is_valid(raise_exception = True)
        user = serializer.validated_data['user']
        token = Token.objects.get_or_create(user = user)
        return Response({
            'token': token
        })

class UserProfile(ListAPIView):
    queryset = User.objects.all()
    # queryset = Mobile.objects.all()

    serializer_class = UserDetailsSerilaizer
    # serializer_class = MobileSerializer

class SignUpView(ListCreateAPIView):
    queryset = User.objects.all()
    serializer_class = SignUpSerializer

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.forms import AuthenticationForm
from accountregistrations.forms import SignUpForm, MobileForm
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm, CartAddProductForms
from django.contrib.auth import get_user
from decimal import Decimal
from django.shortcuts import render_to_response, redirect
from django.core.urlresolvers import reverse
from .models import Carts, CartItem
from shop.models import Product
from django.contrib.auth.decorators import login_required


#----------------For Logged In User---------------

@login_required
def get_user_cart(request):
    """Retrieves the shopping cart for the current user."""
    # If the user is logged in, then grab the user's cart info.
    cart_id = None
    cart = None
    if request.user.is_authenticated and not request.user.is_anonymous:
        try:
            cart = Carts.objects.get(user=request.user)
        except Carts.DoesNotExist:
            cart = Carts(user=request.user)
            cart.save()
    else:
        cart_id = request.session.get('cart_id')
        if not cart_id:
            cart = Carts()
            cart.save()
            request.session['cart_id'] = cart.id
        else:
            cart = Carts.objects.get(id=cart_id)
    return cart

@login_required
def get_cart_count(request):
    #print(request.user)
    cart = get_user_cart(request)
    #print(cart)
    total_count = 0
    cart_items = CartItem.objects.filter(cart=cart)
    for item in cart_items:
        total_count += item.quantity
    return total_count

@login_required
def update_cart_info(request):
    request.session['cart_count'] = get_cart_count(request)


@login_required
def view_cart(request):
    quantity=0
    cart_total_price = None
    user = request.user
    #print(user)
    cart_form = CartAddProductForm()#to update the quantity
    cart = get_object_or_404(Carts, user_id=user.id)
    #print(cart)
    cart_items = CartItem.objects.filter(cart_id=cart.id)
    order_total = Decimal(0.0)
    #print("S")
    for item in cart_items:# getting the total price of the cart
        order_total += (item.product.Price * item.quantity)
        quantity+=item.quantity
        item_cart = Product.objects.filter(id=item.product_id)
        for x in item_cart:
            cart_total_price = item.quantity * x.Price

    context = {    'loop_times': range(1, 21),
                   'quantity':quantity,
                   'user':user,
                   'cart': cart_items,
                   'cart_form':cart_form,
                   'total':cart_total_price,
                   
                   }
    return render(request, 'cart/cart_detail.html', context)


@login_required
def add_to_cart(request, product_id):


    form = CartAddProductForm(request.POST)
    #print("a")
    if form.is_valid():
        #print("b")
        cd = form.cleaned_data
        cart = get_user_cart(request)
        product = Product.objects.get(id=product_id)
        quantity = str(cd['quantity'], )
        # update_quantity = cd['update']
        cart_item = CartItem(product=product, cart=cart, quantity=quantity)

        cart_item.save()



    #print(get_cart_count(request))
    return redirect('cart:view_cart')

@login_required
def update_quantity(request,product_id):
    if request.method == 'POST' and 'quantity' in request.POST:
        get_updated_quantity = request.POST.get('quantity', None)
        updated_item = get_object_or_404(CartItem, product_id=product_id)
        updated_item.quantity = get_updated_quantity
        updated_item.save()

    return redirect('cart:view_cart')

@login_required
def remove_from_cart(request, product_id):
    #print(product_id)

    cart_item = get_object_or_404(CartItem, id=product_id)
    quantity = cart_item.quantity
    cart_item.delete()
    if request.session.get('cart_count'):
        request.session['cart_count'] -= quantity
    else:
        request.session['cart_count'] = 0
    update_cart_info(request)
    return redirect('cart:view_cart')

#---------For Anonymous User's cart------------------

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    
    #print("a")
    form = CartAddProductForms(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')
    
    

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id =product_id)
    cart.remove(product)

    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    
    context = {'loop_times': range(1, 21),
               'cart': cart,
    }

    return render(request, 'cart/ses_cart_detail.html', context)

cart/templates/cart/cart_detail.html
{% extends 'accountregistrations/newbase.html' %}
{% load staticfiles %}
{% load temple_extra %}

{% block title %}
    Your Shopping Cart
{% endblock %}

{% block content2 %}
    <div id="peace-layout">
        {% include 'accountregistrations/header.html' %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <h2>Your Shopping Cart</h2>

                </div>
            </div>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                    <!-- for Authenticated User -->
                    {% for item in cart %}
                        {% for x in item.product_id|products1 %}
                            <tr style="margin-bottom: 15px">
                                <td style="max-width:375px !important;">
                                    <a href="#">
                                        <img {% if x.Photo %} src="{{ x.Photo.url }}" {% endif %}
                                                              alt="{{ x.Product_Name }}"
                                                              style="max-width: 250px !important; padding: 15px">
                                    </a>
                                </td>
                                <td>{{ x.Product_Name }}</td>
                                <td>
                                    <form action="{% url 'cart:update_quantity' x.id %}" method="post" name="update">
                                        <select name="quantity" id="id_quantity">
                                            <!--<option value="1">1</option>-->
                                            {% for x in loop_times %}
                                                <option value={{ x }}>{{ x }}</option>
                                            {% endfor %}
                                        </select>
                                        <input type="submit" class="btn btn-primary" name="update" value="Update"
                                               id="id_update"/>
                                        {% csrf_token %}
                                    </form>
                                </td>
                                <td><a href="{% url 'cart:remove_from_cart' product_id=item.id %}" class="btn" style="color: #FFF;
    background: #F1C152;
    border-color: #CCA242;">Remove</a></td>
                                <td class="num">&#8377;{{ x.Price }}</td>
                                <td class="num">&#8377;{% multiply item.quantity x.Price %}</td>
                            </tr>

                        {% endfor %}
                    {% endfor %}

                    </thead>
                </table>
            </div>

            <div align="center">
                <a href="{% url 'shop:allproducts' %}" class="btn btn-primary">Continue Shopping</a>
                <hr>

                {% if quantity > 0 %}
                    <a href="{% url 'orders:order_create' %}" class="btn btn-primary">Buy Now</a>

                {% elif quantity == 0 %}
                    <a class="launch-modal" data-toggle="modal" data-modal-id="myModal7" style="color:black;">Buy
                        Now</a>
                {% endif %}
                <!-- Modal -->
                <div class="modal fade" id="myModal7" role="dialog">
                    <div class="modal-dialog">
                        <!-- Modal content-->
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">Warning</h4>
                            </div>

                            <div class="modal-body">
                                <span>Add Products to cart to buy</span>
                            </div>


                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <br>
    </div>
{% endblock %}

cart/templates/cart/ses_cart_detail.html
{% extends 'accountregistrations/newbase.html' %}
{% load staticfiles %}
{% load temple_extra %}
{% block title %}
    Your Shopping Cart
{% endblock %}
{% block content2 %}
    <div id="peace-layout">
        {% include 'accountregistrations/header.html' %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 col-xs-12">
                    <h2>Your Shopping Cart</h2>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>


                    <!-- for unauthenticated user-->
                    {% for item in cart %}

                        {% with product=item.product_id %}

                            {% for x in product|products1 %}

                                <tr>
                                    <td>
                                        <a href="#">
                                            <img {% if x.Photo %} src="{{ x.Photo.url }}" {% else %}
                                                                  alt="{{ x.Product_Name }}" {% endif %}
                                                                  style="max-width: 350px !important;">
                                        </a>

                                    </td>
                                    <td>{{ x.Product_Name }}</td>
                                    <td>

                                        <form action="{% url 'cart:cart_add' x.id %}" method="post">

                                            <select name="quantity" id="id_quantity">
                                                <option value="1" selected>1</option>
                                                {% for x in loop_times %}
                                                    <option value={{ x }}>{{ x }}</option>
                                                {% endfor %}
                                            </select>
                                            <input type="submit" name="update" value="Update" id="id_update"
                                                   style="margin-left:10px;" class="btn btn-primary"/>
                                            {% csrf_token %}

                                        </form>
                                    </td>
                                    <td><a href="{% url 'cart:cart_remove' x.id %}" class="btn" style="color: #FFF;
    background: #F1C152;
    border-color: #CCA242;">Remove</a></td>
                                    <td class="num">&#8377;{{ item.price }}</td>
                                    <td class="num">&#8377;{{ item.total_price }}</td>
                                </tr>
                            {% endfor %}
                        {% endwith %}
                    {% endfor %}
                    </thead>
                </table>
            </div>

            <p align="center">
                <a href="{% url 'shop:allproducts' %}">
                    <button class="fa fa-shopping btn btn-primary" >Continue Shopping</button>
                </a>
                <br>
                <a href="{% url 'accountregistrations:Login' %}">
                    Login
                </a>
                /<a href="{% url 'accountregistrations:Login' %}" >
                    SignUp
                </a> as a <strong style="color:red">User</strong> to Buy


            </p>
        </div>
    </div>
{% endblock %}