accountregistrations/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from accountregistrations import views
from django.conf import settings


urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^signupManager/$', views.signup1, name='signup1'),
    
    url(r'^login/$', views.Login, name='Login'),

    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),

    # -----------For gmail login-------------
    url(r'^auth/complete/google-oauth2/Usertype/$', views.Usertype, name='Usertype'),

    # -----------For Facebook login-----------
    url(r'^auth/complete/facebook/Usertype/$', views.Usertype, name='Usertype'),

    # -------------For Password Reset----------------------

    url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'registrations/password_reset_form.html'},
        name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done,
        {'template_name': 'registrations/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name': 'registrations/password_reset_confirm.html'},
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,
        {'template_name': 'registrations/password_reset_complete.html'}, name='password_reset_complete'),

    # ------------ For knowing the type of users-------------
    url(r'^login/Usertype/$', views.Usertype, name='Usertype'),
    url(r'^api/user/', include('accountregistrations.api.urls', namespace = 'api-user-login'))

]

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #for UN-authenticated user
    url(r'^cart_detail/$', views.cart_detail, name='cart_detail'),
    url(r'^cart_add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^cart_remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),

    #for authenticated user
    url(r'^$', views.view_cart, name='view_cart'),
    url(r'^add/(?P<product_id>\d+)/$', views.add_to_cart, name='add_to_cart'),
    url(r'^update_quantity/(?P<product_id>\d+)/$', views.update_quantity, name='update_quantity'),
    url(r'^remove/(?P<product_id>\d+)/$', views.remove_from_cart, name='remove_from_cart'),
]

darshan/api/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    TempleListApiView,
    TempleCreateApiView,
    TempleDetailApiView,
    TempleUpdateApiView,
    TempleDeleteApiView,
)

urlpatterns = [
    url(r'^temple_list/$', TempleListApiView.as_view(), name='temple_list'),
    url(r'^temple_list/create/$', TempleCreateApiView.as_view(), name='temple_create'),
    url(r'^temple_list/detail/(?P<pk>\d+)/$', TempleDetailApiView.as_view(), name='temple_detail'),
    url(r'^temple_list/update/(?P<pk>\d+)/$', TempleUpdateApiView.as_view(), name='temple_update'),
    url(r'^temple_list/delete/(?P<pk>\d+)/$', TempleDeleteApiView.as_view(), name='temple_delete'),


]

darshan/urls.py
from django.conf.urls import url, include
from darshan import views


urlpatterns = [

    url(r'^$', views.home, name='home'),
    url(r'^user_profile/$', views.user_profile, name='user_profile'),
    url(r'^manager_profile/$', views.manager_profile, name='manager_profile'),
    url(r'^selectedDarshan/$', views.selectedDharshan, name='accounts'),
    url(r'^details/(?P<temp>.+)$', views.details, name='details'),
    url(r'^detail/(?P<temp1>.+)$', views.detail, name='detail'),
    url(r'^selectedTemple/(?P<pk>\d+)$', views.selectedTemple, name='selectedTemple'),
    url(r'^allPrasad/(?P<pk>\d+)$', views.all_Prasad, name='all_Prasad'),
    url(r'^delete/(?P<value>.+)/$', views.delete, name='delete'),
    url(r'^temple_gallery/2col$', views.temple_gallery_2col, name='temple_gallery_2col'),
    url(r'^temple_gallery/default$', views.temple_gallery_default, name='temple_gallery_default'),
    # ------------ For Temples--------
    url(r'^temple_add/$', views.temple_add, name='temple_add'),
    url(r'^temple_update/(?P<s>.+)/$', views.temple_update, name='temple_update'),
    url(r'^temple_remove/(?P<s>.+)/$', views.temple_remove, name='temple_remove'),

    # ------------- For Pictures----------
    url(r'^picture_add/$', views.picture_add, name='picture_add'),
    url(r'^picture_update/(?P<s1>.+)/$', views.picture_update, name='picture_update'),
    url(r'^picture_remove/(?P<s1>.+)/$', views.picture_remove, name='picture_remove'),

    # -----------For Darshans------------
    url(r'^darshan_add/$', views.darshan_add, name='darshan_add'),
    url(r'^darshan_update/(?P<s2>.+)/$', views.darshan_update, name='darshan_update'),
    url(r'^darshan_remove/(?P<s2>.+)/$', views.darshan_remove, name='darshan_remove'),
    url(r'^alldarshan/$', views.allDarshan, name='alldarshan'),

    # ----------------For Prasad-----------------

    url(r'^prasad_add/$', views.prasad_add, name='prasad_add'),
    url(r'^prasad_update/(?P<p>.+)/$', views.prasad_update, name='prasad_update'),
    url(r'^prasad_remove/(?P<p>.+)/$', views.prasad_remove, name='prasad_remove'),

    url(r'^tmp/', include('darshan.api.urls', namespace='temple'))

]

shop/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth import views as auth_views
from darshan import views
from shop import views as core_views
from django.conf import settings

urlpatterns = [
    url(r'^allproducts/$', core_views.allproducts, name='allproducts'),
    url(r'^productdetails/(?P<pk>\d+)$', core_views.details1, name='details1'),

    # ----------For Shopkeeper-------------
    url(r'^seller_profile/$', core_views.seller_profile, name='seller_profile'),

    # ------------ For Shopkeeper--------
    url(r'^product_add/$', core_views.product_add, name='product_add'),
    url(r'^product_update/(?P<p>.+)/$', core_views.product_update, name='product_update'),
    url(r'^product_remove/(?P<p>.+)/$', core_views.product_remove, name='product_remove'),
    url(r'^product_api/', include('shop.api.urls'), name='product_api'),

]

temple/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from shop import views as core_views
#from django.views.i18n import javascript_catalog


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('accountregistrations.urls', namespace='accountregistrations')),
    url(r'', include('darshan.urls', namespace='darshan')),
    url(r'', include('shop.urls', namespace='shop')),
    url(r'cart/', include('cart.urls', namespace='cart')),
    url(r'orders/', include('orders.urls', namespace='orders')),
    url(r'^notifications/', include('notify.urls', namespace='notifications')),
    #url(r'^pay/', include('payu_biz.urls', namespace='pay')),
    #url(r'^search/', include('haystack.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url('^', include('django.contrib.auth.urls')),
    #url(r'^admin/jsi18n', javascript_catalog),
    url(r'^api/temple/', include('darshan.api.urls', namespace='api-temple')),

]

urlpatterns += [
       url(r'^api-auth/', include('rest_framework.urls'))
]
handler400 = core_views.error400  # noqa
handler403 = core_views.error403  # noqa
handler404 = core_views.error404  # noqa
handler500 = core_views.error500  # noqa
handler200 = core_views.error200  # noqa


# when debug is True

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG is False:
#     urlpatterns += [url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
#                     url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}), ]

darshan/models.py
from __future__ import unicode_literals
from django.utils import timezone
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.postgres.fields import ArrayField
from dirtyfields import DirtyFieldsMixin
import datetime
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied


class Temples(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    temple2 = models.CharField(max_length=250, default=None)
    Display_image = models.ImageField(
        null=True, blank=True,
        height_field="height_field",
        width_field="width_field")
    Latest_to_be_updated_image = models.ImageField(
        null=True, blank=True,
        height_field="height_field",
        width_field="width_field")
    height_field = models.IntegerField(default=None, blank=True, null=True)
    width_field = models.IntegerField(default=None, blank=True,null=True)
    Deity = models.CharField(max_length=100, default=None)
    About_Temple = models.TextField(default=None)
    City = models.CharField(max_length=40, default=None)
    Contacts = models.CharField(max_length=300, default=None)
    Phone_Number = models.CharField(max_length=300, default=None)
    Address = models.TextField(default=None)
    Email = models.EmailField()
    Temple_Purohit = models.CharField(max_length=250, default=None)
    Religion = models.CharField(max_length=200, default="Hindu", blank=True, null=True)  # About temple
    Related_Faith = models.TextField(default=None, blank=True, null=True)
    Website = models.URLField(default=None, blank=True, null=True)
    Temple_History = models.TextField(default=None, blank=True, null=True)
    Significance = models.TextField(default=None, blank=True, null=True)
    Celebration = models.TextField(default=None, blank=True, null=True)
    Live_Darshan_link = models.URLField(default=None, blank=True, null=True)
    Management = models.TextField(default=None, blank=True, null=True)
    Other_Deities = models.TextField(default=None, blank=True, null=True)
    Related_Temple = models.TextField(default=None, blank=True, null=True)
    Accomodation_Link = models.URLField(default=None, blank=True, null=True)  # TempleFacilities
    Annakshetra = models.BooleanField(default=False)
    Online_Pooja = models.URLField(default=None, blank=True, null=True)
    Online_Donation = models.URLField(default=None, blank=True, null=True)
    Online_Prasad = models.URLField(default=None, blank=True, null=True)
    Online_Facility = models.URLField(default=None, blank=True, null=True)
    Transportation = models.TextField(default=None, blank=True, null=True)
    About_City = models.TextField(default=None, blank=True, null=True)  # visit Temple
    How_To_Reach = models.TextField(default=None, blank=True, null=True)
    Do_And_Dont = models.TextField(default=None, blank=True, null=True)
    Amenities = models.TextField(default=None, blank=True, null=True)
    Precaution_While_Visiting = models.TextField(default=None, blank=True, null=True)
    State = models.CharField(max_length=50, default=None, blank=True, null=True)
    Country = models.CharField(max_length=60, default=None, blank=True, null=True)
    Tender = models.FileField(upload_to='file_uploads/', blank=True, null=True)  # Temple Miscelleneous
    Recruitment = models.TextField(default=None, blank=True, null=True)
    Notice_and_Updates = models.TextField(default=None, blank=True, null=True)

    def __str__(self):
        return self.temple2


    def file_link(self):
        if self.Tender:
            return '<a href="%s">download</a>' % (self.Tender.url)
        else:
            return "No attachment"
    file_link.allow_tags = True

    class Meta:
        ordering = [
            'temple2'
        ]


class Picture(DirtyFieldsMixin, models.Model):#TO BE CALLED AS "DARSHANS"---------------------
    Temple = models.ForeignKey(Temples, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(
        null=True, blank=True,
        height_field="height_field",
        width_field="width_field")
    height_field = models.IntegerField(default=None, null=True, blank=True)
    width_field = models.IntegerField(default=None, null=True, blank=True)
    Time = models.TimeField(auto_now_add=False, auto_now=False, null=True, blank=True)
    Ritual = models.CharField(max_length=200, default=None)
    publish = models.DateField(auto_now_add=False, auto_now=False,default=datetime.date.today)
    timestamp = models.DateField(auto_now=False, auto_now_add=True)
    updated = models.DateField(auto_now=True, auto_now_add=False)

    # objects = PostManager()
    def __unicode__(self):
        return self.Temple.temple2

    def __str__(self):
        return str(self.Temple.temple2) + ',' + str(self.Ritual)


# class Meta:
# ordering = ['-timestamp','-updated']#important

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Select_Temple = ArrayField(models.CharField(max_length=250, default=None, blank=True, null=True), default=list,
                               blank=True, null=True)
    selected = ArrayField(models.IntegerField(default=None), default=list, blank=True, null=True)

    def __str__(self):
        return self.user.username

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    post_save.connect(create_user_profile, sender=User)





class Darshans(models.Model):#TO BE CALLED "TEMPLE TIMINGS"-------------------
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    temple = models.ForeignKey(Temples, on_delete=models.CASCADE)
    rituals = models.CharField(max_length=250, default=None)
    timings = models.CharField(max_length=250, default=None)

    def __str__(self):
        return str(self.rituals)


class TempleManager(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="temple_manager")
    is_manager = models.BooleanField(default=False)
    Temple_Name = models.CharField(max_length=100, default=None)

    def __str__(self):
        return self.user.username

darshan/api/views.py
from rest_framework.generics import (
    ListAPIView,
    CreateAPIView,
    RetrieveAPIView,
    UpdateAPIView,
    DestroyAPIView,
    RetrieveUpdateAPIView
)
# Use for Permission
from rest_framework.permissions import (
    AllowAny,
    IsAdminUser,
    IsAuthenticated,
    IsAuthenticatedOrReadOnly
)
# For search filter
from rest_framework.filters import (
    SearchFilter,
    OrderingFilter
)

# For serializing the field
from .serializers import (
    TempleListSerializer,
    TempleDetailSerializer,
    TempleCreateSerializer
)

from .pagination import (
    TempleLimitOffsetPagination,
    TemplePageNumberPagination
)

from .permission import (
    IsOwnerOrReadOnly,
    IsTempleManager
)

from darshan.models import Temples


# ListAPIView is used for retriving all the list
class TempleListApiView(ListAPIView):
    serializer_class = TempleListSerializer
    permission_classes = [AllowAny]
    # pagination_class = TemplePageNumberPagination

    # Use rest_framework for searching way
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['temple2', 'user_id__username']
    # To-Do:: Order by Temple_id
    queryset = Temples.objects.all().order_by()


class TempleCreateApiView(CreateAPIView):
    permission_classes = [IsTempleManager, IsAuthenticated]
    serializer_class = TempleCreateSerializer
    queryset = Temples.objects.all()


class TempleDetailApiView(RetrieveAPIView):
    permission_classes = [AllowAny]
    serializer_class = TempleDetailSerializer
    queryset = Temples.objects.all()


class TempleUpdateApiView(RetrieveUpdateAPIView):
    permission_classes = [IsOwnerOrReadOnly, IsAuthenticatedOrReadOnly]
    serializer_class = TempleDetailSerializer
    queryset = Temples.objects.all()


class TempleDeleteApiView(DestroyAPIView):
    print("Coming to Temple Delete API View")
    permission_classes = [IsOwnerOrReadOnly, IsAuthenticatedOrReadOnly]
    serializer_class = TempleDetailApiView
    queryset = Temples.objects.all()

darshan/templates/darshan/allPrasad.html
{% extends 'accountregistrations/newbase.html' %}
{% load staticfiles %}
{% load temple_extra %}
{% block content2 %}
    <div id="peace-layout">
        {% include 'accountregistrations/header.html' %}
        <div class="container" style="margin-top: 15px">
        <div class="row">
            {% for pra in prasad %}
                <div class="col-sm-3">
                    <div class="thumbnail">
                        <img class="image-container img-responsive roundedCorner"
                        {% if pra.Photo %} src="{{ pra.Photo.url }}" {% else %} alt="{{ pra.Product_Name }}" {% endif %} 
                              style="min-width: 150px">
                        {{ pra.Product_Name }}<br>
                        {{ pra.Price }}
                        
                        <a href="{% url 'shop:details1' pk=pra.id %}">
                            <button class="btn btn-default" style="float: right;margin-bottom: 10px;">
                                Buy Now
                            </button>
                        </a>

                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    </div>
{% endblock%}

darshan/templates/darshan/darshan_add.html
{% extends 'accountregistrations/newbase.html' %}
{% load crispy_forms_tags %}
{% block content2 %}
    <style>
        form #inputButton {
            float: unset !important;
        }

        input {
            float: right !important;
        }

        input[type=text] {
            width: 42%;
        }

        input[type=url] {
            width: 42%;
        }

        input[type=email] {
            width: 42%;
        }

        input[type=file] {
            width: 42%;
        }

        input[type="checkbox"] {
            margin-right: 10px;
            float: unset !important;
        }

        input[type=time] {
            width: 42%;
        }

        input[type=number] {
            width: 42%;
        }

        input[type=password] {
            width: 42%;
        }

        .select2-container--default {
            width: 50% !important;
        }

        .select2-search__field {
            width: 375px !important;
        }

        textarea {
            float: right;
        }

        #id_Temple_Name {
            float: right;
        }

    </style>
{#    <script src="https://code.jquery.com/jquery-2.2.4.min.js"#}
{#            integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="#}
{#            crossorigin="anonymous"></script>#}
{#    <script type="text/javascript">#}
{#        $(window).load(function () {#}
{#            $('#errors').modal('show');#}
{#        });#}
{#    </script>#}
{#    {% include 'darshan/error_message.html' %}#}
    <div id="peace-layout">
        {% include 'accountregistrations/header.html' %}
        <div class="container" style="margin-top: 15px">
            <div class="row">
                <div class="col-md-12">
                    <h2 align="center">Darshan Form</h2>
                    <br>
                    <form method="Post" role="form" enctype="multipart/form-data">
                        {% for field in dar_add_form %}
                            <p>
                                <label for="{{ field.auto_id }}">{{ field.label_tag }}
                                    {% if field.field.required %}
                                        <span class="required" style="color: red;">*</span>
                                    {% endif %}
                                </label>

                                {{ field }}

                            </p>
                            {% if field.errors %}
                                <div class="alert alert-danger">
                                    {{ field.errors }}
                                </div>
                            {% endif %}
                            <br>
                        {% endfor %}
                        {% csrf_token %}
                        <p align="center">
                            <button type="submit" value="Save" class="btn btn-primary"
                                    style="width: 100px; background-color: #f1c152;">
                                Save
                            </button>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <style>
        .wmd-input {
            height: auto;
        }

        .wmd-preview {
            height: auto;
        }
    </style>
{% endblock %}

darshan/templates/darshan/error_message.html
{% if messages %}
        <div class="modal" id="errors" style="display: flex !important;">
            <div class="modal-dialog">
                <div class="v-cell">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span
                                    aria-hidden="true">&times;</span><span
                                    class="sr-only">Close</span></button>
                            <h4 class="modal-title" style="color: red;text-align: center;font-weight: 600;font-size: 20px;
                                font-family: sans-serif;">Message</h4>
                        </div>

                        <div class="modal-body">
                            <div class="messages" style="text-align: left;margin-bottom: 0px;">
                                {% for message in messages %}
                                    <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                                {% endfor %}
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    {% endif %}

darshan/templates/darshan/include_delete_modal.html
<!-- Modal -->
  <div class="modal fade" id="{{var}}" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title" style="color: red;text-align: center;font-weight: 600;font-size: 40px;
          font-family: sans-serif;">Warning</h4>
        </div>
        <div class="modal-body">
          <p>Do you want to delete it???</p>
        </div>
        <div class="modal-footer">
         <a href="{% url 'darshan:delete' value=x %}"><button type="button" class="btn btn-default" style="color: black;">Yes</button></a>
         <button type="button" class="btn btn-default" data-dismiss="modal" style="color: black;"> No </button>
        </div>
      </div>
      
    </div>
  </div> 

darshan/templates/darshan/message_display.html
 <div id="modal">
			  <div class="modal-dialog">
			    <div class="v-cell">
			      <div class="modal-content">
			        <div class="modal-header">
			          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			          <h4 class="modal-title">Modal title</h4>
			        </div>
		{% if messages %}
		<div class="modal-body">
		    <ul class="messages" style="text-align: left;background-color: red; margin-bottom: 0px;">
		        {% for message in messages %}
		            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
		        {% endfor %}
		    </ul>
		</div>
		{% endif %}
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          
        </div>
      </div>
    </div>
  </div>
</div>
		
      
		
		 
    

darshan/templates/darshan/user_profile.html
{% extends "accountregistrations/newbase.html" %}
{% load staticfiles %}
{% load temple_extra %}
{% block content2 %}

    {% block style1 %}
        <style>
            .select2-container--default {
                width: 50% !important;
            }

            .select2-search__field {
                width: 375px !important;
            }

        </style>
    {% endblock %}
    <div id="peace-layout">
        {% include 'accountregistrations/header.html' %}
        <div class="container" style="margin-top:15px;">
            <div class="row">
                <div class="col-md-12" align="right">
                    <p>
                        <label>Name:</label>
                        <span>{{ u.first_name }}</span><span> {{ u.last_name }}</span>
                    </p>
                    {% if v %}
                        <p>
                            {% if v.Mobile_Number %}
                                <label>Mobile Number:</label>
                                <span>{{ v.Mobile_Number }}</span>
                            {% endif %}
                        </p>
                    {% endif %}
                    {% if u.email %}
                        <p>
                            <label>Email:</label>
                            <span>{{ u.email }}</span>
                        </p>
                    {% endif %}
                </div>
            </div>
            <hr>

            <div class="row">
                <div class="col-md-12" align="center">
                    <form action="{% url 'darshan:user_profile' %}" method="post" role="form">
                        {% csrf_token %}
                        {{ form.as_table }}
                        <button class="btn btn-primary" type="submit">Add</button>
                    </form>
                    <br>
                </div>
            </div>

            {% if object_list %}

                <p style="text-align: center;"> ADD TIME FROM DROPDOWN </p>
                <div class="row">
                    <div class="col-md-12">
                        <form action="{% url 'darshan:user_profile' %}" method="post"
                              style="width: 100% !important;"> {% csrf_token %}
                            {% for x in object_list %}
                                <div class="row">
                                    <div class="col-md-8 col-offset-4">

                                        <div class="row">
                                            <div class="col-md-2">
                                                <label for="id_Temple1">
                                                    {{ x }}
                                                </label>
                                            </div>
                                            <div class="col-md-2">
                                                <a style="color: white" class="launch-modal btn btn-primary"
                                                   data-toggle="modal" data-modal-id="{{ x|removechar }}"
                                                   data-backdrop="static">
                                                    Delete
                                                </a>
                                                {% include 'darshan/include_delete_modal.html' with var=x|removechar %}
                                            </div>
                                            <div class="col-md-8">
                                                {% for y in x|temple %}
                                                    <td>
                                                        <select class="django-select" name="{{ x }}"
                                                                multiple="multiple">
                                                            {% with temp=y|picture %}
                                                                {% for z in temp %}
                                                                    <option value="{{ z.id }}"
                                                                            {% for x1 in query_list.selected %}
                                                                                {% if x1 == z.id %} selected
                                                                                {% endif %}{% endfor %}>
                                                                        {{ z.Ritual }}
                                                                    </option>
                                                                {% endfor %}
                                                            {% endwith %}
                                                        </select>
                                                    </td>
                                                    <br>
                                                {% endfor %}
                                            </div>
                                        </div>
                                        <br>

                                    </div>
                                </div>
                            {% endfor %}
                            <p style="text-align: center">

                                <button class="btn btn-primary" type="submit">Add</button>

                            </p>
                        </form>
                    </div>
                </div>
            {% endif %}
            <hr>
            <div class="row">
                <div class="col-md-12" align="center">
                    <a href="{% url 'darshan:accounts' %}" style="color: white">
                        <button class="btn btn-primary">
                            Ready for Darshan
                        </button>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12" align="center">
                    <div class="pagination">
                    <span class="step-links">
                        {% if object_list.has_previous %}
                            <a href="?{{ page_change_var }}=1">&laquo; first</a>
                            <a href="?{{ page_change_var }}={{ object_list.previous_page_number }} {% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
                        {% endif %}
                        <span class="current">
                            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
                        </span>
                        {% if object_list.has_next %}
                            <a href="?{{ page_change_var }}={{ object_list.next_page_number }} {% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
                            <a href="?{{ page_change_var }}={{ object_list.paginator.num_pages }} ">last &raquo;</a>
                        {% endif %}
                    </span>
                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock %}