cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #for UN-authenticated user
    url(r'^cart_detail/$', views.cart_detail, name='cart_detail'),
    url(r'^cart_add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^cart_remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),

    #for authenticated user
    url(r'^$', views.view_cart, name='view_cart'),
    url(r'^add/(?P<product_id>\d+)/$', views.add_to_cart, name='add_to_cart'),
    url(r'^update_quantity/(?P<product_id>\d+)/$', views.update_quantity, name='update_quantity'),
    url(r'^remove/(?P<product_id>\d+)/$', views.remove_from_cart, name='remove_from_cart'),
]

shop/api/urls.py
from django.conf.urls import url, include

from .views import ProductView, ProductDetailView, ProductRemoveView

urlpatterns = [
    url(r'^products/$', ProductView.as_view(), name='product-list'),
    url(r'^product/(?P<pk>[0-9]+)/$', ProductDetailView.as_view(), name='product-detail'),
    url(r'^product_remove/(?P<pk>[0-9]+)/$', ProductRemoveView.as_view(), name='product-remove'),

]

shop/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth import views as auth_views
from darshan import views
from shop import views as core_views
from django.conf import settings

urlpatterns = [
    url(r'^allproducts/$', core_views.allproducts, name='allproducts'),
    url(r'^productdetails/(?P<pk>\d+)$', core_views.details1, name='details1'),

    # ----------For Shopkeeper-------------
    url(r'^seller_profile/$', core_views.seller_profile, name='seller_profile'),

    # ------------ For Shopkeeper--------
    url(r'^product_add/$', core_views.product_add, name='product_add'),
    url(r'^product_update/(?P<p>.+)/$', core_views.product_update, name='product_update'),
    url(r'^product_remove/(?P<p>.+)/$', core_views.product_remove, name='product_remove'),
    url(r'^product_api/', include('shop.api.urls'), name='product_api'),

]

temple/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from shop import views as core_views
#from django.views.i18n import javascript_catalog


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('accountregistrations.urls', namespace='accountregistrations')),
    url(r'', include('darshan.urls', namespace='darshan')),
    url(r'', include('shop.urls', namespace='shop')),
    url(r'cart/', include('cart.urls', namespace='cart')),
    url(r'orders/', include('orders.urls', namespace='orders')),
    url(r'^notifications/', include('notify.urls', namespace='notifications')),
    #url(r'^pay/', include('payu_biz.urls', namespace='pay')),
    #url(r'^search/', include('haystack.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url('^', include('django.contrib.auth.urls')),
    #url(r'^admin/jsi18n', javascript_catalog),
    url(r'^api/temple/', include('darshan.api.urls', namespace='api-temple')),

]

urlpatterns += [
       url(r'^api-auth/', include('rest_framework.urls'))
]
handler400 = core_views.error400  # noqa
handler403 = core_views.error403  # noqa
handler404 = core_views.error404  # noqa
handler500 = core_views.error500  # noqa
handler200 = core_views.error200  # noqa


# when debug is True

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG is False:
#     urlpatterns += [url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
#                     url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}), ]

shop/models.py
from django.db import models
from darshan.models import Temples
from django.contrib.postgres.fields import ArrayField
from dirtyfields import DirtyFieldsMixin
from django.contrib.auth.models import User


# Create your models here.

class Shopkeeper(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="shopkeeper")
    is_shopkeeper = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user)


class Product(DirtyFieldsMixin, models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    Product_Name = models.CharField(max_length=250, default=None)
    Temple_Name = models.ForeignKey(Temples, on_delete=models.CASCADE, blank=False)
    Out_of_Stock = models.BooleanField(default=False)
    Price = models.DecimalField(max_digits=19, decimal_places=2, default=None)
    Photo = models.ImageField(
        null=True, blank=True,
        height_field="height_field",
        width_field="width_field")
    Photo1 = models.ImageField(
        null=True, blank=True,
        height_field="height_field",
        width_field="width_field")
    Photo2 = models.ImageField(
        null=True, blank=True,
        height_field="height_field",
        width_field="width_field")
    Photo3 = models.ImageField(
        null=True, blank=True,
        height_field="height_field",
        width_field="width_field")
    Photo4 = models.ImageField(
        null=True, blank=True,
        height_field="height_field",
        width_field="width_field")
    Photo5 = models.ImageField(
        null=True, blank=True,
        height_field="height_field",
        width_field="width_field")
    Photo6 = models.ImageField(
        null=True, blank=True,
        height_field="height_field",
        width_field="width_field")
    height_field = models.IntegerField(default=None, null=True, blank=True)
    width_field = models.IntegerField(default=None, null=True, blank=True)
    Offer_or_Discount = models.CharField(max_length=50, default=None, blank=True, null=True)
    is_Prasad = models.BooleanField(default=False)
    Product_Description = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.Product_Name)

    class Meta:
        ordering = [
            'Price'
        ]


# class Photo(models.Model):
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     photos = models.ImageField(
#         null=True, blank=True,
#         height_field="height_field",
#         width_field="width_field")
#     height_field = models.IntegerField(default=None, null=True, blank=True)
#     width_field = models.IntegerField(default=None, null=True, blank=True)
#
#     def __str__(self):
#         return self.product


class ProductSelected(models.Model):
    products = ArrayField(models.IntegerField(default=None, blank=True, null=True), default=list, blank=True, null=True)

    def __str__(self):
        return self.id

shop/forms.py
from django import forms
from shop.models import Product
from pagedown.widgets import PagedownWidget
from django.forms import ClearableFileInput



class ProductAddForm(forms.ModelForm):
    Product_Name = forms.CharField(required=True)
    Price = forms.DecimalField(required=True)
    is_Prasad = forms.BooleanField(required=False)
    Product_Description = forms.CharField(widget=PagedownWidget, required=True)
    Out_of_Stock = forms.BooleanField(required=False)
    Offer_or_Discount = forms.CharField(required=False)
    Photo=forms.ImageField(required=False,widget=ClearableFileInput)

    class Meta:
        model = Product
        fields = ('Temple_Name', 'Product_Name', 'Out_of_Stock', 'Price', 'Photo','Photo1','Photo2','Photo3','Photo4','Photo5','Photo6','Offer_or_Discount',
                  'is_Prasad','Product_Description')

# class ProductExtraImagesForm(forms.ModelForm):
#
#     class Meta:
#         model = Photo
#         fields = ('photos','height_field','width_field')
# class CustomSearchForm(ModelSearchForm):
#     order_choices = [('y', 'Descending'), ('n', 'Ascending')]
#     order = forms.ChoiceField(choices=order_choices, widget=forms.RadioSelect(), required=False)

#     def search(self):
#         sqs = super(CustomSearchForm, self).search()
#         if not self.is_valid():
#             return self.no_query_found()

#         if self.cleaned_data['order'] == 'y':
#             sqs = sqs.order_by('-Price')
#         else:
#             sqs = sqs.order_by('Price')
#         return sqs

shop/api/views.py
from django.http import HttpResponse, Http404
from rest_framework import status
from rest_framework.generics import ListCreateAPIView,DestroyAPIView, RetrieveUpdateAPIView
from rest_framework.permissions import IsAuthenticatedOrReadOnly

# from shop.api.permission import IsOwnerOrReadOnly, IsAllowed
from rest_framework.response import Response

from .serializers import ProductSerializers
from shop.models import Product
from django.views.decorators.csrf import csrf_exempt

class ProductView(ListCreateAPIView):
    queryset = Product.objects.all()
    permission_classes =  [ IsAuthenticatedOrReadOnly]
    serializer_class = ProductSerializers

    def perform_create(self, serializer):
        # print(IsAllowed, IsAuthenticatedOrReadOnly, self.request.user)
        try:
            if(self.request.user.temple_manager.is_manager or self.request.user.shopkeeper.is_shopkeeper):
                serializer.save()
            else:

                return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

        except:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class ProductDetailView(RetrieveUpdateAPIView):
    permission_classes = [ IsAuthenticatedOrReadOnly]
    serializer_class = ProductSerializers
    queryset = Product.objects.all()

class ProductRemoveView(DestroyAPIView):
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = ProductSerializers
    queryset = Product.objects.all()

shop/views.py
from django.contrib.auth.decorators import login_required
from temple.decorators import user_is_shopkeeper
from django.shortcuts import render, redirect
from django.db.models import Q
from darshan.models import Temples
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from cart.forms import CartAddProductForm, CartAddProductForms
from django.contrib.auth.models import User
from django.contrib import messages
from shop.forms import ProductAddForm
from shop.models import Product
from cart.models import CartItem
from notify.signals import notify
from cart.models import Carts


# class ProductSearch(SearchView):
#     template = 'search/search.html'
#     form_name = CustomSearchForm


def allproducts(request):
    # print(request.user)
    lists = None
    k = []

    if request.method == 'POST' and 'temples' in request.POST:
        lists = request.POST.getlist('temples', None)
        # print(list)

    temple = Temples.objects.all()
    query = request.GET.get("q")
    queryset_list = Temples.objects.all()
    if query:
        queryset_list = queryset_list.filter(Q(temple2__icontains=query) |
                                             Q(City__icontains=query) |
                                             Q(Country__icontains=query) |
                                             Q(Deity__icontains=query) |
                                             Q(State__icontains=query)).distinct().order_by('temple2')
    context = {

        'k': k,
        'query_list': queryset_list,
        'list': lists,
        'b': temple,
    }
    return render(request, 'shop/allproduct.html', context)


def details1(request, pk):
    # print(val)
    user = request.user
    product = Product.objects.filter(id=pk).first()
    related_products= Product.objects.filter(Q(Temple_Name_id=product.Temple_Name_id)|Q(Product_Name=product.Product_Name)).distinct()
    cart_product_form = CartAddProductForm()
    cart_product_forms = CartAddProductForms()
    context = {'product': product,
               'loop_times': range(2, 21),
               'cart_product_form': cart_product_form,
               'cart_product_forms': cart_product_forms,
               'user': user,
               'related_products':related_products}
    return render(request, 'shop/details.html', context)


# ---------For Shopkeeper -----------------

@login_required
@user_is_shopkeeper
def seller_profile(request):
    shopkeeper = get_object_or_404(User, id=request.user.id)
    items = Product.objects.filter(seller=shopkeeper)
    context = {
        'items': items
    }
    return render(request, "shop/seller_profile.html", context)


@login_required
@user_is_shopkeeper
def product_add(request):
    user = request.user
    shopkeeper = get_object_or_404(User, id=user.id)
    if request.method=="POST":
        item_add_form = ProductAddForm(request.POST or None, request.FILES or None)
        if item_add_form.is_valid():
            instance = item_add_form.save(commit=False)
            instance.seller = shopkeeper
            instance.save()
            messages.success(request,'Product is added')
            return redirect('shop:seller_profile')
        else:
            messages.error(request, item_add_form.errors)
            item_add_form = ProductAddForm(request.POST)
    else:
        item_add_form=ProductAddForm()

    context = {'item_add_form': item_add_form, }

    return render(request, 'shop/item_add.html', context)


@login_required
@user_is_shopkeeper
def product_update(request, p=None):
    user = request.user
    seller = get_object_or_404(User, id=user.id)
    instance = get_object_or_404(Product, id=p)
    if request.POST:
        item_add_form = ProductAddForm(request.POST or None, request.FILES or None, instance=instance)

        if item_add_form.is_valid() == True:
            instances = item_add_form.save(commit=False)

            if instance.is_dirty():
                dirty_fields = instance.get_dirty_fields()
                # print(dirty_fields)
                for field in dirty_fields:
                    if field == 'Out_of_Stock' and instance.Out_of_Stock == True:
                        us = []
                        user1 = User.objects.filter(is_superuser=False)
                        user = CartItem.objects.filter(product_id=instance.id)
                        for x in user:
                            users = get_object_or_404(Carts, id=x.cart_id)
                            c = get_object_or_404(User, id=users.user_id)
                            us.append(c)

                        if not us:
                            recipient = user1
                        else:
                            recipient = us
                        notify.send(sender=seller, target=instance, recipient_list=list(recipient), verb="Out of stock")
                        for person in recipient:
                            subject = 'Notification from Divya Kripa:Your Order'
                            verb = "Out of Stock"
                            message = render_to_string('darshan/notification_email.html', {
                                'target': instance, 'verb': verb})
                            person.email_user(subject, message)
                            # send_verification_mail(person.email, message, subject)
                    if field == 'Out_of_Stock' and instance.Out_of_Stock == False:
                        us = []
                        user1 = User.objects.filter(is_superuser=False)
                        user = CartItem.objects.filter(product_id=instance.id)
                        for x in user:
                            users = get_object_or_404(Carts, id=x.cart_id)
                            c = get_object_or_404(User, id=users.user_id)
                            us.append(c)

                        if not us:
                            recipient = user1
                        else:
                            recipient = us
                        notify.send(sender=seller, target=instance, recipient_list=list(recipient), verb="Available")
                        for person in recipient:
                            subject = 'Notification from Divya Kripa:Your Order'
                            verb = "Available"
                            message = render_to_string('darshan/notification_email.html', {
                                'target': instance, 'verb': verb})
                            person.email_user(subject, message)
                            #send_verification_mail(person.email, message, subject)

            instances.save()
            messages.success(request,'Product is updated')
            return redirect('shop:seller_profile')
    else:
        item_add_form=ProductAddForm()

    context = {
        'item_add_form': item_add_form,
    }

    return render(request, 'shop/item_add.html', context)


@login_required
@user_is_shopkeeper
def product_remove(request, p):
    # print("fbvbf")
    instance = get_object_or_404(Product, id=p)
    # print(instance)
    instance.delete()
    messages.success(request,'Product is removed')
    return redirect('shop:seller_profile')


def error400(request):
    return render(request, 'shop/error/HTTP400.html')


def error403(request):
    return render(request, 'shop/error/HTTP403.html')


def error404(request):
    return render(request, 'shop/error/HTTP404.html')


def error500(request):
    return render(request, 'shop/error/HTTP500.html')


def error200(request):
    return render(request, 'shop/error/HTTP500.html')

shop/templates/shop/details.html
{% extends 'accountregistrations/newbase.html' %}
{% load staticfiles %}
{% load temple_extra %}
{% block content2 %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <div id="peace-layout">
        {% include 'accountregistrations/header.html' %}
        <div class="container" style="margin-top: 15px;">
            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-5 col-sm-12 col-xs-12" id="picZoomer">
                        <img id="myimage"  {% if product.Photo %} src="{{ product.Photo.url }}" {% else %}
                             alt="{{ product.Product_Name }}" {% endif %} class="img-responsive"
                             style="max-width: 100% !important; ">
                        {#                        <ul class="piclist">#}
                        {#                            {% if product.Photo %}#}
                        {#                                <li><img src="{{ product.Photo.url }}" alt="photo"></li>{% endif %}#}
                        {#                            {% if product.Photo1 %}#}
                        {#                                <li><img src="{{ product.Photo1.url }}" alt="photo1"></li>{% endif %}#}
                        {#                            {% if product.Photo2 %}#}
                        {#                                <li><img src="{{ product.Photo2.url }}" alt="photo2"></li>{% endif %}#}
                        {#                            {% if product.Photo3 %}#}
                        {#                                <li><img src="{{ product.Photo3.url }}" alt="photo3"></li>{% endif %}#}
                        {#                            {% if product.Photo4 %}#}
                        {#                                <li><img src="{{ product.Photo4.url }}" alt="photo4"></li>{% endif %}#}
                        {#                            {% if product.Photo5 %}#}
                        {#                                <li><img src="{{ product.Photo5.url }}" alt="photo5"></li>{% endif %}#}
                        {##}
                        {#                        </ul>#}
                    </div>
                    <div class="col-md-7 col-xs-12 col-sm-12">

                        <h3>
                            {{ product.Product_Name }}
                        </h3>
                        <p>
                            <br>
                            &#8377;{{ product.Price }}
                        </p>
                        <p>

                            {% if product.Offer_or_Discount %}
                                <strong>Offer or Discount: </strong>
                                {{ product.Offer_or_Discount }}
                            {% endif %}
                        </p>
                        <p>

                            <strong>Description: </strong>
                        <div class="content-markdown">{{ product.Product_Description }}</div>

                        </p>
                        <br><br>
                        <p>
                            {% if user.is_authenticated %}
                                <form action="{% url 'cart:add_to_cart' product.id %}" method="post">
                                    {{ cart_product_form }}
                                    {% csrf_token %}
                                    <div>
                                         <input class="btn" type="submit" value="Add to Cart"
                                               style="color: #FFF;background: #F1C152;border-color: #CCA242;width: auto;font-size: 13px;border-radius: 3px;text-transform: uppercase;font-weight: bold;">
                                    </div>
                                    <!--add Product Description-->
                                </form>
                            {% elif not user.is_authenticated and not user.is_superuser %}
                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    {{ cart_product_forms }}
                                    {% csrf_token %}
                                    <div>
                                        <input class="btn" type="submit" value="Add to Cart"
                                               style="color: #FFF;background: #F1C152;border-color: #CCA242;width: auto;font-size: 13px;border-radius: 3px;text-transform: uppercase;font-weight: bold;">
                                    </div>
                                    <!--add Product Description-->
                                </form>
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>

            <br><br>
            <hr>
            <div class="row">
                <div id="features" class="features uk-container uk-margin-large-top">
                    <h3 class="title-deco uk-text-center title-text color-black-a54"
                        style="text-align: center;margin-top: 0;margin-bottom: 40px;">
                        <span class="triangle-up"></span>
                        <span class="triangle-down"></span>
                        <span class="heading" style="color:#555; font-weight: 700; font-family: 'Roboto', sans-serif;">SIMILAR PRODUCTS</span>
                        <span class="triangle-up"></span>
                        <span class="triangle-down"></span>
                    </h3>
                </div>
            </div>
            <div class="row">
                {% for products in related_products %}

                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <a href="{% url 'shop:details1' pk=products.id %}">
                            <div class="thumbnail">
                                <img {% if products.Photo %} src="{{ products.Photo.url }}" {% else %}
                                                             alt="{{ products.Product_Name }}" {% endif %}
                                                             class="img-responsive">
                            </div>
                        </a>
                    </div>

                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/shop/item_add.html
{% extends 'accountregistrations/newbase.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content2 %}
    {% block head_extra %}
        {{ item_add_form.media }}
    {% endblock head_extra %}
    <style>
        form #inputButton {
            float: unset !important;
        }

        input {
            float: right !important;
        }

        input[type=text] {
            width: 42%;
        }

        input[type=url] {
            width: 42%;
        }

        input[type=email] {
            width: 42%;
        }

        input[type=file] {
            width: 42%;
        }

        input[type="checkbox"] {
            margin-right: 10px;
            float: unset !important;
        }

        input[type=time] {
            width: 42%;
        }

        input[type=number] {
            width: 42%;
        }

        input[type=password] {
            width: 42%;
        }

        .select2-container--default {
            width: 50% !important;
        }

        .select2-search__field {
            width: 375px !important;
        }

        textarea {
            float: right;
        }

        #id_Temple_Name {
            float: right;
        }

    </style>
{#    <script src="https://code.jquery.com/jquery-2.2.4.min.js"#}
{#            integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="#}
{#            crossorigin="anonymous"></script>#}
{#    <script type="text/javascript">#}
{#        $(window).load(function () {#}
{#            $('#errors').modal('show');#}
{#        });#}
{#    </script>#}
{#    {% include 'darshan/error_message.html' %}#}
    <div id="peace-layout">
        {% include 'accountregistrations/header.html' %}
        <div class="container" style="margin-top: 15px;">
            <div class="row">
                <div class="col-md-12">
                    <h2>Product Form</h2>
                    <form method="Post" role="form" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in item_add_form %}
                            <p>
                                <label for="{{ field.auto_id }}">{{ field.label_tag }}
                                    {% if field.field.required or field.field.blank %}
                                        <span class="required" style="color: red;">*</span>
                                    {% endif %}
                                </label>
                                {{ field }}
                                {% if field.errors %}
                                    <div class="alert alert-danger">
                                        {{ field.errors }}
                                    </div>
                                {% endif %}
                            <br>
                            </p>
                        {% endfor %}
                        <p align="center">
                            <button type="submit" value="Save" class="btn btn-primary"
                                    style="width: 100px; background-color: #f1c152;">
                                Save
                            </button>
                        </p>

                    </form>
                </div>
            </div>
        </div>
    </div>
    <style>
        .wmd-input {
            height: auto;
        }

        .wmd-preview {
            height: auto;
        }

    </style>
{% endblock %}

shop/templates/shop/seller_profile.html
{% extends 'accountregistrations/newbase.html' %}
{% block content2 %}
    <div id="peace-layout">
    {% include 'accountregistrations/header.html' %}
        <div class="container" style="margin-top: 15px">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12 mark_button">
                    PRODUCTS
                    <span>
                        <a href="{% url 'shop:product_add' %}">
                            <button class="btn btn-primary" style="margin-left: 20px;">
                                Add PRODUCTS<strong> +</strong>
                            </button>
                        </a>
                    </span>
                    <br><br><br><br>
                    {% for y in items %}

                        <div class="col-md-12">
                            <div class="col-md-6">

                        
                            <a href="{% url 'shop:product_update' p=y.id %}" style="color: black; font-family: sans-serif">
                               <h4> {{ y.Product_Name }}, {{ y.Temple_Name }} </h4>
                            </a>
                                
                            </div>

                            <div class="col-md-6">
                                <button class="btn btn-primary" data-toggle="modal" data-target="#myModal5"
                                        data-backdrop='static'>
                                    Remove
                                </button>
                                <div class="modal fade" id="myModal5" role="dialog">
                                    <div class="modal-dialog">
                                        <!-- Modal content-->
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">&times;
                                                </button>
                                                <h4 class="modal-title">Warning</h4>
                                            </div>
                                            <div class="modal-body">
                                                <p>Do you want to delete it???</p>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="{% url 'shop:product_remove' p=y.id %}">
                                                    <button type="button" class="btn btn-default">Yes</button>
                                                </a>
                                                <a href="{% url 'shop:seller_profile' %}">
                                                    <button type="button" class="btn btn-default"> No</button>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- Modal -->

                            <br>
                            <br>
                            <hr>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}